tag @s remove origins:power_silver_stings
tag @s[scores={od:hold=296..299}] add origins:power_silver_stings
tag @s[scores={od:hold=307}] add origins:power_silver_stings
tag @s[scores={od:hold=331}] add origins:power_silver_stings
tag @s[scores={od:hold=355}] add origins:power_silver_stings
tag @s[scores={od:ohold=355}] add origins:power_silver_stings
tag @s[scores={od:hold=360..369}] add origins:power_silver_stings
tag @s[scores={od:hold=391}] add origins:power_silver_stings
tag @s[scores={od:hold=421}] add origins:power_silver_stings
tag @s[scores={od:hold=575}] add origins:power_silver_stings
tag @s[scores={od:hold=601}] add origins:power_silver_stings
tag @s[scores={od:head=4}] add origins:power_silver_stings
tag @s[scores={od:chest=4}] add origins:power_silver_stings
tag @s[scores={od:legs=4}] add origins:power_silver_stings
tag @s[scores={od:feet=4}] add origins:power_silver_stings
event entity @s[tag=!origins:power_silver_stinging,tag=origins:power_silver_stings] origins:damage_over_time_0.25
event entity @s[tag=origins:power_silver_stinging,tag=!origins:power_silver_stings] origins:damage_over_time_end
tag @s[tag=!origins:power_silver_stinging,tag=origins:power_silver_stings] add origins:power_silver_stinging
tag @s[tag=origins:power_silver_stinging,tag=!origins:power_silver_stings] remove origins:power_silver_stinging