scoreboard objectives add c_bee dummy
scoreboard objectives add t_bee dummy
scoreboard objectives add c_cow dummy
scoreboard objectives add t_cow dummy
scoreboard objectives add c_dire_wolf dummy
scoreboard objectives add t_dire_wolf dummy
scoreboard objectives add c_fox dummy
scoreboard objectives add t_fox dummy
scoreboard objectives add c_frogling dummy
scoreboard objectives add t_frogling dummy
scoreboard objectives add c_goat dummy
scoreboard objectives add t_goat dummy
scoreboard objectives add c_rabbit dummy
scoreboard objectives add t_rabbit dummy
scoreboard objectives add c_raccoonl dummy
scoreboard objectives add t_raccoonl dummy
scoreboard objectives add c_sheep dummy
scoreboard objectives add t_sheep dummy
scoreboard objectives add c_slime dummy
scoreboard objectives add t_slime dummy
scoreboard objectives add c_starborne dummy
scoreboard objectives add t_starborne dummy
scoreboard objectives add c_strider dummy
scoreboard objectives add t_strider dummy
scoreboard objectives add c_tmotd dummy
scoreboard objectives add t_tmotd dummy
scoreboard objectives add c_witherin dummy
scoreboard objectives add t_witherin dummy