tag @s[tag=origins:power1_use] remove origins:power1_use
tag @s[tag=origins:power1_hit] remove origins:power1_hit
tag @s[tag=origins:power2_use] remove origins:power2_use
tag @s[tag=origins:power2_hit] remove origins:power2_hit
tag @s[tag=origins:power3_use] remove origins:power3_use
tag @s[tag=origins:power3_hit] remove origins:power3_hit
tag @s[tag=origins:power4_use] remove origins:power4_use
tag @s[tag=origins:power4_hit] remove origins:power4_hit
tag @s[tag=origins:power5_use] remove origins:power5_use
tag @s[tag=origins:power5_hit] remove origins:power5_hit
tag @s[tag=origins:power6_use] remove origins:power6_use
tag @s[tag=origins:power6_hit] remove origins:power6_hit
tag @s remove origins:power_used