scoreboard objectives add c_human dummy
scoreboard objectives add t_human dummy
scoreboard objectives add c_arachnid dummy
scoreboard objectives add t_arachnid dummy
scoreboard objectives add c_avian dummy
scoreboard objectives add t_avian dummy
scoreboard objectives add c_blazeborn dummy
scoreboard objectives add t_blazeborn dummy
scoreboard objectives add c_elytrian dummy
scoreboard objectives add t_elytrian dummy
scoreboard objectives add c_enderian dummy
scoreboard objectives add t_enderian dummy
scoreboard objectives add c_feline dummy
scoreboard objectives add t_feline dummy
scoreboard objectives add c_merling dummy
scoreboard objectives add t_merling dummy
scoreboard objectives add c_phantom dummy
scoreboard objectives add t_phantom dummy
scoreboard objectives add c_shulk dummy
scoreboard objectives add t_shulk dummy