replaceitem entity @s slot.inventory 0 origins:locked_slot
replaceitem entity @s slot.inventory 1 origins:locked_slot
replaceitem entity @s slot.inventory 2 origins:locked_slot
replaceitem entity @s slot.inventory 3 origins:locked_slot
replaceitem entity @s slot.inventory 5 origins:locked_slot
replaceitem entity @s slot.inventory 6 origins:locked_slot
replaceitem entity @s slot.inventory 7 origins:locked_slot
replaceitem entity @s slot.inventory 8 origins:locked_slot
replaceitem entity @s slot.inventory 9 origins:locked_slot
replaceitem entity @s slot.inventory 10 origins:locked_slot
replaceitem entity @s slot.inventory 11 origins:locked_slot
replaceitem entity @s slot.inventory 15 origins:locked_slot
replaceitem entity @s slot.inventory 16 origins:locked_slot
replaceitem entity @s slot.inventory 17 origins:locked_slot
replaceitem entity @s slot.inventory 18 origins:locked_slot
replaceitem entity @s slot.inventory 19 origins:locked_slot
replaceitem entity @s slot.inventory 20 origins:locked_slot
replaceitem entity @s slot.inventory 21 origins:locked_slot
replaceitem entity @s slot.inventory 23 origins:locked_slot
replaceitem entity @s slot.inventory 24 origins:locked_slot
replaceitem entity @s slot.inventory 25 origins:locked_slot
replaceitem entity @s slot.inventory 26 origins:locked_slot