replaceitem entity @s slot.inventory 0 air
replaceitem entity @s slot.inventory 1 air
replaceitem entity @s slot.inventory 2 air
replaceitem entity @s slot.inventory 6 air
replaceitem entity @s slot.inventory 7 air
replaceitem entity @s slot.inventory 8 air
replaceitem entity @s slot.inventory 9 air
replaceitem entity @s slot.inventory 10 air
replaceitem entity @s slot.inventory 11 air
replaceitem entity @s slot.inventory 15 air
replaceitem entity @s slot.inventory 16 air
replaceitem entity @s slot.inventory 17 air
replaceitem entity @s slot.inventory 18 air
replaceitem entity @s slot.inventory 19 air
replaceitem entity @s slot.inventory 20 air
replaceitem entity @s slot.inventory 24 air
replaceitem entity @s slot.inventory 25 air
replaceitem entity @s slot.inventory 26 air