execute @s[scores={od:hold=262,od:using=1}] ~~~ function origins/powers/inedible/porkchop
execute @s[scores={od:hold=263,od:using=1}] ~~~ function origins/powers/inedible/cooked_porkchop
execute @s[scores={od:hold=264,od:using=1}] ~~~ function origins/powers/inedible/cod
execute @s[scores={od:hold=265,od:using=1}] ~~~ function origins/powers/inedible/salmon
execute @s[scores={od:hold=266,od:using=1}] ~~~ function origins/powers/inedible/tropical_fish
execute @s[scores={od:hold=267,od:using=1}] ~~~ function origins/powers/inedible/pufferfish
execute @s[scores={od:hold=268,od:using=1}] ~~~ function origins/powers/inedible/cooked_cod
execute @s[scores={od:hold=269,od:using=1}] ~~~ function origins/powers/inedible/cooked_salmon
execute @s[scores={od:hold=273,od:using=1}] ~~~ function origins/powers/inedible/beef
execute @s[scores={od:hold=274,od:using=1}] ~~~ function origins/powers/inedible/cooked_beef
execute @s[scores={od:hold=275,od:using=1}] ~~~ function origins/powers/inedible/chicken
execute @s[scores={od:hold=276,od:using=1}] ~~~ function origins/powers/inedible/cooked_chicken
execute @s[scores={od:hold=277,od:using=1}] ~~~ function origins/powers/inedible/rotten_flesh
execute @s[scores={od:hold=278,od:using=1}] ~~~ function origins/powers/inedible/spider_eye
execute @s[scores={od:hold=288,od:using=1}] ~~~ function origins/powers/inedible/rabbit
execute @s[scores={od:hold=289,od:using=1}] ~~~ function origins/powers/inedible/cooked_rabbit
execute @s[scores={od:hold=290,od:using=1}] ~~~ function origins/powers/inedible/rabbit_stew
execute @s[scores={od:hold=550,od:using=1}] ~~~ function origins/powers/inedible/mutton
execute @s[scores={od:hold=551,od:using=1}] ~~~ function origins/powers/inedible/cooked_mutton
execute @s[scores={od:hold=200003,od:using=1}] ~~~ function origins/powers/inedible/modified_beef
execute @s[scores={od:hold=200008,od:using=1}] ~~~ function origins/powers/inedible/modified_chicken
execute @s[scores={od:hold=200010,od:using=1}] ~~~ function origins/powers/inedible/modified_cod
execute @s[scores={od:hold=200011,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_beef
execute @s[scores={od:hold=200012,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_chicken
execute @s[scores={od:hold=200013,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_cod
execute @s[scores={od:hold=200014,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_mutton
execute @s[scores={od:hold=200015,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_porkchop
execute @s[scores={od:hold=200016,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_rabbit
execute @s[scores={od:hold=200017,od:using=1}] ~~~ function origins/powers/inedible/modified_cooked_salmon
execute @s[scores={od:hold=200027,od:using=1}] ~~~ function origins/powers/inedible/modified_mutton
execute @s[scores={od:hold=200029,od:using=1}] ~~~ function origins/powers/inedible/modified_porkchop
execute @s[scores={od:hold=200031,od:using=1}] ~~~ function origins/powers/inedible/modified_pufferfish
execute @s[scores={od:hold=200033,od:using=1}] ~~~ function origins/powers/inedible/modified_rabbit_stew
execute @s[scores={od:hold=200034,od:using=1}] ~~~ function origins/powers/inedible/modified_rabbit
execute @s[scores={od:hold=200035,od:using=1}] ~~~ function origins/powers/inedible/modified_rotten_flesh
execute @s[scores={od:hold=200036,od:using=1}] ~~~ function origins/powers/inedible/modified_salmon
execute @s[scores={od:hold=200037,od:using=1}] ~~~ function origins/powers/inedible/modified_spider_eye
execute @s[scores={od:hold=200039,od:using=1}] ~~~ function origins/powers/inedible/modified_tropical_fish