scoreboard objectives add dummy_value dummy
scoreboard objectives add origin_count dummy
scoreboard objectives add origin_ecount dummy
scoreboard objectives add origin_groupid dummy
scoreboard objectives add origin_groups dummy
scoreboard objectives add origin_selectid dummy
scoreboard objectives add origin_playerid dummy
scoreboard objectives add od:health dummy
scoreboard objectives add od:mhealth dummy
scoreboard objectives add od:hold dummy
scoreboard objectives add od:ohold dummy
scoreboard objectives add od:using dummy
scoreboard objectives add od:use_time dummy
scoreboard objectives add od:jumping dummy
scoreboard objectives add od:dj dummy
scoreboard objectives add od:sneaking dummy
scoreboard objectives add od:on_ground dummy
scoreboard objectives add od:moving dummy
scoreboard objectives add od:sprinting dummy
scoreboard objectives add od:swimming dummy
scoreboard objectives add od:gliding dummy
scoreboard objectives add od:sleeping dummy
scoreboard objectives add od:attacking dummy
scoreboard objectives add od:hurting dummy
scoreboard objectives add od:water dummy
scoreboard objectives add od:rain dummy
scoreboard objectives add od:splashed dummy
scoreboard objectives add od:alive dummy
scoreboard objectives add od:day dummy
scoreboard objectives add od:on_fire dummy
scoreboard objectives add od:ridden dummy
scoreboard objectives add od:riding dummy
scoreboard objectives add od:head dummy
scoreboard objectives add od:chest dummy
scoreboard objectives add od:legs dummy
scoreboard objectives add od:feet dummy
scoreboard objectives add od:dim dummy
scoreboard objectives add od:fire dummy
scoreboard objectives add od:lava dummy
scoreboard objectives add od:underground dummy
scoreboard objectives add od:underwater dummy
scoreboard objectives add od:temp dummy
scoreboard objectives add odw:health dummy
scoreboard objectives add odw:mhealth dummy
scoreboard objectives add odw:hold dummy
scoreboard objectives add odw:ohold dummy
scoreboard objectives add odw:using dummy
scoreboard objectives add odw:use_time dummy
scoreboard objectives add odw:jumping dummy
scoreboard objectives add odw:dj dummy
scoreboard objectives add odw:sneaking dummy
scoreboard objectives add odw:on_ground dummy
scoreboard objectives add odw:moving dummy
scoreboard objectives add odw:sprinting dummy
scoreboard objectives add odw:swimming dummy
scoreboard objectives add odw:gliding dummy
scoreboard objectives add odw:sleeping dummy
scoreboard objectives add odw:attacking dummy
scoreboard objectives add odw:hurting dummy
scoreboard objectives add odw:water dummy
scoreboard objectives add odw:rain dummy
scoreboard objectives add odw:splashed dummy
scoreboard objectives add odw:alive dummy
scoreboard objectives add odw:day dummy
scoreboard objectives add odw:on_fire dummy
scoreboard objectives add odw:ridden dummy
scoreboard objectives add odw:riding dummy
scoreboard objectives add odw:head dummy
scoreboard objectives add odw:chest dummy
scoreboard objectives add odw:legs dummy
scoreboard objectives add odw:feet dummy
scoreboard objectives add odw:dim dummy
scoreboard objectives add odw:fire dummy
scoreboard objectives add odw:lava dummy
scoreboard objectives add odw:underground dummy
scoreboard objectives add odw:underwater dummy
scoreboard objectives add odw:temp dummy