scoreboard players set @s od:health 20
scoreboard players set @s od:mhealth 20
scoreboard players set @s od:hold 0
scoreboard players set @s od:ohold 0
scoreboard players set @s od:using 0
scoreboard players set @s od:use_time 0
scoreboard players set @s od:jumping 0
scoreboard players set @s od:dj 0
scoreboard players set @s od:sneaking 0
scoreboard players set @s od:on_ground 1
scoreboard players set @s od:moving 0
scoreboard players set @s od:sprinting 0
scoreboard players set @s od:swimming 0
scoreboard players set @s od:gliding 0
scoreboard players set @s od:sleeping 0
scoreboard players set @s od:attacking 0
scoreboard players set @s od:hurting 0
scoreboard players set @s od:water 0
scoreboard players set @s od:rain 0
scoreboard players set @s od:splashed 0
scoreboard players set @s od:alive 1
scoreboard players set @s od:day 1
scoreboard players set @s od:on_fire 0
scoreboard players set @s od:ridden 0
scoreboard players set @s od:riding 0
scoreboard players set @s od:head 0
scoreboard players set @s od:chest 0
scoreboard players set @s od:legs 0
scoreboard players set @s od:feet 0
scoreboard players set @s od:dim 0
scoreboard players set @s od:fire 0
scoreboard players set @s od:lava 0
scoreboard players set @s od:underground 0
scoreboard players set @s od:underwater 0
scoreboard players set @s od:temp 0
scoreboard players set @s odw:health 20
scoreboard players set @s odw:mhealth 20
scoreboard players set @s odw:hold 0
scoreboard players set @s odw:ohold 0
scoreboard players set @s odw:using 0
scoreboard players set @s odw:use_time 0
scoreboard players set @s odw:jumping 0
scoreboard players set @s odw:dj 0
scoreboard players set @s odw:sneaking 0
scoreboard players set @s odw:on_ground 1
scoreboard players set @s odw:moving 0
scoreboard players set @s odw:sprinting 0
scoreboard players set @s odw:swimming 0
scoreboard players set @s odw:gliding 0
scoreboard players set @s odw:sleeping 0
scoreboard players set @s odw:attacking 0
scoreboard players set @s odw:hurting 0
scoreboard players set @s odw:water 0
scoreboard players set @s odw:rain 0
scoreboard players set @s odw:splashed 0
scoreboard players set @s odw:alive 1
scoreboard players set @s odw:day 1
scoreboard players set @s odw:on_fire 0
scoreboard players set @s odw:ridden 0
scoreboard players set @s odw:riding 0
scoreboard players set @s odw:head 0
scoreboard players set @s odw:chest 0
scoreboard players set @s odw:legs 0
scoreboard players set @s odw:feet 0
scoreboard players set @s odw:dim 0
scoreboard players set @s odw:fire 0
scoreboard players set @s odw:lava 0
scoreboard players set @s odw:underground 0
scoreboard players set @s odw:underwater 0
scoreboard players set @s odw:temp 0