tag @s add origins:power_shock_absorption_activate
tag @s[scores={odw:head=..2,od:head=3..6}] remove origins:power_shock_absorption_activate
tag @s[tag=origins:power_shock_absorption_activate,scores={odw:chest=..2,od:chest=3..6}] remove origins:power_shock_absorption_activate
tag @s[tag=origins:power_shock_absorption_activate,scores={odw:chest=7,od:chest=3..6}] remove origins:power_shock_absorption_activate
tag @s[tag=origins:power_shock_absorption_activate,scores={odw:legs=..2,od:legs=3..6}] remove origins:power_shock_absorption_activate
tag @s[tag=origins:power_shock_absorption_activate,scores={odw:feet=..2,od:feet=3..6}] remove origins:power_shock_absorption_activate
tag @s[tag=origins:power_shock_absorption_activate,tag=!origins:damage_modification_0.75x] add origins:damage_modification_0.75x
tag @s[tag=origins:power_shock_absorption_activate,tag=!origins:damage_modification_projectiles_0.5x] add origins:damage_modification_projectiles_0.5x
tag @s[tag=!origins:power_shock_absorption_activate,tag=origins:damage_modification_0.75x] remove origins:damage_modification_0.75x
tag @s[tag=!origins:power_shock_absorption_activate,tag=origins:damage_modification_projectiles_0.5x] remove origins:damage_modification_projectiles_0.5x
tag @s[tag=origins:power_shock_absorption_activate] remove origins:power_shock_absorption_activate