execute @s[scores={od:hold=257,od:using=1}] ~~~ function origins/powers/inedible/apple
execute @s[scores={od:hold=258,od:using=1}] ~~~ function origins/powers/inedible/golden_apple
execute @s[scores={od:hold=259,od:using=1}] ~~~ function origins/powers/inedible/enchanted_golden_apple
execute @s[scores={od:hold=260,od:using=1}] ~~~ function origins/powers/inedible/mushroom_stew
execute @s[scores={od:hold=261,od:using=1}] ~~~ function origins/powers/inedible/bread
execute @s[scores={od:hold=270,od:using=1}] ~~~ function origins/powers/inedible/dried_kelp
execute @s[scores={od:hold=271,od:using=1}] ~~~ function origins/powers/inedible/cookie
execute @s[scores={od:hold=272,od:using=1}] ~~~ function origins/powers/inedible/melon_slice
execute @s[scores={od:hold=279,od:using=1}] ~~~ function origins/powers/inedible/carrot
execute @s[scores={od:hold=280,od:using=1}] ~~~ function origins/powers/inedible/potato
execute @s[scores={od:hold=281,od:using=1}] ~~~ function origins/powers/inedible/baked_potato
execute @s[scores={od:hold=282,od:using=1}] ~~~ function origins/powers/inedible/poisonous_potato
execute @s[scores={od:hold=283,od:using=1}] ~~~ function origins/powers/inedible/golden_carrot
execute @s[scores={od:hold=284,od:using=1}] ~~~ function origins/powers/inedible/pumpkin_pie
execute @s[scores={od:hold=285,od:using=1}] ~~~ function origins/powers/inedible/beetroot
execute @s[scores={od:hold=286,od:using=1}] ~~~ function origins/powers/inedible/beetroot_soup
execute @s[scores={od:hold=287,od:using=1}] ~~~ function origins/powers/inedible/sweet_berries
execute @s[scores={od:hold=290,od:using=1}] ~~~ function origins/powers/inedible/rabbit_stew
execute @s[scores={od:hold=558,od:using=1}] ~~~ function origins/powers/inedible/chorus_fruit
execute @s[scores={od:hold=589,od:using=1}] ~~~ function origins/powers/inedible/suspicious_stew
execute @s[scores={od:hold=592,od:using=1}] ~~~ function origins/powers/inedible/honey_bottle
execute @s[scores={od:hold=10001,od:using=1}] ~~~ function origins/powers/inedible/glow_berries
execute @s[scores={od:hold=200001,od:using=1}] ~~~ function origins/powers/inedible/modified_apple
execute @s[scores={od:hold=200002,od:using=1}] ~~~ function origins/powers/inedible/modified_baked_potato
execute @s[scores={od:hold=200004,od:using=1}] ~~~ function origins/powers/inedible/modified_beetroot_soup
execute @s[scores={od:hold=200005,od:using=1}] ~~~ function origins/powers/inedible/modified_beetroot
execute @s[scores={od:hold=200006,od:using=1}] ~~~ function origins/powers/inedible/modified_bread
execute @s[scores={od:hold=200007,od:using=1}] ~~~ function origins/powers/inedible/modified_carrot
execute @s[scores={od:hold=200009,od:using=1}] ~~~ function origins/powers/inedible/modified_chorus_fruit
execute @s[scores={od:hold=200018,od:using=1}] ~~~ function origins/powers/inedible/modified_cookie
execute @s[scores={od:hold=200019,od:using=1}] ~~~ function origins/powers/inedible/modified_dried_kelp
execute @s[scores={od:hold=200020,od:using=1}] ~~~ function origins/powers/inedible/modified_enchanted_golden_apple
execute @s[scores={od:hold=200021,od:using=1}] ~~~ function origins/powers/inedible/modified_glow_berries
execute @s[scores={od:hold=200022,od:using=1}] ~~~ function origins/powers/inedible/modified_golden_apple
execute @s[scores={od:hold=200023,od:using=1}] ~~~ function origins/powers/inedible/modified_golden_carrot
execute @s[scores={od:hold=200024,od:using=1}] ~~~ function origins/powers/inedible/modified_honey_bottle
execute @s[scores={od:hold=200025,od:using=1}] ~~~ function origins/powers/inedible/modified_melon_slice
execute @s[scores={od:hold=200026,od:using=1}] ~~~ function origins/powers/inedible/modified_mushroom_stew
execute @s[scores={od:hold=200028,od:using=1}] ~~~ function origins/powers/inedible/modified_poisonous_potato
execute @s[scores={od:hold=200030,od:using=1}] ~~~ function origins/powers/inedible/modified_potato
execute @s[scores={od:hold=200032,od:using=1}] ~~~ function origins/powers/inedible/modified_pumpkin_pie
execute @s[scores={od:hold=200033,od:using=1}] ~~~ function origins/powers/inedible/modified_rabbit_stew
execute @s[scores={od:hold=200038,od:using=1}] ~~~ function origins/powers/inedible/modified_sweet_berries